version: "2"

linters:
  default: none
  enable:
    - durationcheck
    - errcheck
    - forcetypeassert
    - godot
    - ineffassign
    - makezero
    - misspell
    - nilerr
    - predeclared
    - staticcheck
    - unconvert
    - unparam
    - unused
    - govet

formatters:
  enable:
    - gofmt